spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
            scope: profile
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
          github:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
          line:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
            provider: LINE
            scope: profile
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          LINE:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/v2/profile
            user-name-attribute: userId 
