spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 257675311126-gc9q8cnq7c4qguaiuh6os3b8gd9k06p3.apps.googleusercontent.com
            client-secret: LP_DFcbfOVo36vPbHEe6eSt7
            scope: profile
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
          github:
            client-id: aca70059b03ed6b4b810
            client-secret: 60fc9961d098b8fe4494114cb38ebd10acb16b11
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
          facebook:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
          line:
            client-id: 1565591582
            client-secret: 5460831f372b5bb2f84bda2cfbe12bee
            provider: LINE
            scope: profile
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          LINE:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/v2/profile
            user-name-attribute: userId 